import {Link, NavLink, Route, Routes} from "./router";

const services=[
  ["Software & SaaS Products","Designing, building and operating useful software products from concept to launch."],
  ["AI Agents & Automation","Creating AI-assisted workflows, agents and automation for focused business tasks."],
  ["Web Applications","Secure, responsive platforms, dashboards and internal operational systems."],
  ["Mobile Applications","Android and cross-platform products designed for everyday use and distribution."],
  ["Websites & Digital Experiences","High-performance websites that explain products clearly and support growth."],
  ["Cloud & Integrations","Firebase, APIs, authentication, data workflows and connected digital infrastructure."],
];

const products=[
  {name:"Orion HQ",url:"https://orionhq.space",type:"Operations platform",text:"A digital control environment for organising applications, workflows and operational activity."},
  {name:"Mini Post App",url:"https://minipostapp.space",type:"AI content product",text:"A structured workspace for planning and creating story-led social media content."},
  {name:"TextSpeeder",url:"https://textspeeder.online",type:"Productivity software",text:"A digital writing and text-productivity product focused on faster, clearer workflows."},
  {name:"AccountPilot",url:"https://accountpilot.space",type:"Privacy-focused software",text:"A product for discovering and organising online accounts connected to authorised email addresses."},
  {name:"Caelum HQ",url:"https://caelumhq.space",type:"Digital platform",text:"An ANM Digital product brand currently in active development."},
  {name:"Roman Times",url:"https://romantimes.online",type:"Digital publishing",text:"An online publishing brand for history-led digital content."},
  {name:"PhotoBeauty",url:"",type:"Mobile application",text:"A mobile photo-enhancement product designed for simple, accessible image improvement."},
  {name:"99 Names of Allah",url:"",type:"Mobile application",text:"A mobile reference experience centred on the 99 Names of Allah."},
];

function Header(){return <header className="nav"><Link className="brand" to="/"><span>ANM</span><b>Digital</b></Link><nav><NavLink to="/services">Capabilities</NavLink><NavLink to="/products">Products</NavLink><NavLink to="/about">Company</NavLink><NavLink to="/contact">Contact</NavLink></nav><Link className="button small" to="/contact">Build with us</Link></header>}
function Footer(){return <footer><div><Link className="brand" to="/"><span>ANM</span><b>Digital</b></Link><p>Digital products, software and AI systems.<br/>Operated by Yoga Products Ltd.</p></div><div className="footlinks"><Link to="/products">Products</Link><Link to="/services">Capabilities</Link><Link to="/about">Company</Link><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><a href="https://github.com/ANM-Digital" target="_blank" rel="noreferrer">GitHub ↗</a></div><small>© 2026 ANM Digital. All rights reserved.</small></footer>}
function Shell({children}:{children:React.ReactNode}){return <><Header/><main>{children}</main><Footer/></>}
function Tag({children}:{children:React.ReactNode}){return <p className="tag">{children}</p>}
function Hero({tag,title,copy}:{tag:string,title:string,copy:string}){return <section className="pagehero"><Tag>{tag}</Tag><h1>{title}</h1><p className="lead">{copy}</p></section>}

function Home(){return <Shell><section className="hero"><div><Tag>Digital product company</Tag><h1>We turn ideas into <em>working digital products.</em></h1><p className="lead">ANM Digital creates software, SaaS products, mobile applications, AI agents, automation, websites and the cloud systems behind them.</p><div className="actions"><Link className="button" to="/products">Explore our products →</Link><Link className="textlink" to="/about">About ANM Digital</Link></div></div><div className="visual"><strong>BUILD</strong><span>SOFTWARE</span><span>SAAS</span><span>MOBILE</span><span>AI</span></div></section><section className="proof"><span>Product creation</span><span>Applied AI</span><span>Mobile & web</span><span>Cloud infrastructure</span></section><section><Tag>What we create</Tag><div className="heading"><h2>Digital capability from product strategy to production.</h2><Link to="/services">View all capabilities →</Link></div><div className="grid3">{services.map(([name,text],i)=><article className="card" key={name}><b>0{i+1}</b><h3>{name}</h3><p>{text}</p></article>)}</div></section><section className="light"><Tag>Product portfolio</Tag><div className="heading"><h2>Independent brands. Real digital products.</h2><Link to="/products">Full portfolio →</Link></div><div className="productgrid">{products.slice(0,4).map((p,i)=><ProductCard key={p.name} product={p} index={i}/>)}</div></section><section className="companystrip"><div><Tag>Company structure</Tag><h2>A focused digital business with commercial foundations.</h2></div><p>ANM Digital is the digital product division operated by Yoga Products Ltd. It is separate in positioning from A&M Consultancy and focuses on creating, developing and operating digital assets and software products.</p></section><section className="cta"><Tag>Build something useful</Tag><h2>From first concept to a product people can use.</h2><Link className="button white" to="/contact">Start a conversation →</Link></section></Shell>}

function ProductCard({product:p,index}:{product:typeof products[number],index:number}){const body=<article className={`product p${index%4}`}><p className="tag">{p.type}</p><h3>{p.name}</h3><p>{p.text}</p><b>{p.url?"Visit product ↗":"Mobile product"}</b></article>;return p.url?<a href={p.url} target="_blank" rel="noreferrer">{body}</a>:body}
function Services(){return <Shell><Hero tag="Capabilities" title="Everything needed to create and operate digital products." copy="We combine product thinking, design, engineering, AI and cloud infrastructure in one practical delivery capability."/><section><div className="grid3">{services.map(([name,text],i)=><article className="card" key={name}><b>0{i+1}</b><h2>{name}</h2><p>{text}</p></article>)}</div></section></Shell>}
function Products(){return <Shell><Hero tag="Our products" title="A growing portfolio of independent digital brands." copy="ANM Digital develops and operates products across productivity, operations, content, privacy, publishing and mobile experiences."/><section><div className="productgrid all">{products.map((p,i)=><ProductCard key={p.name} product={p} index={i}/>)}</div></section></Shell>}
function About(){return <Shell><Hero tag="Company" title="A digital product business built to create." copy="ANM Digital exists to develop useful digital assets—not only to advise other businesses about them."/><section className="twocol"><div><h2>How the group is organised</h2><p><b>Yoga Products Ltd</b> is the operating company behind two distinct business identities.</p><p><b>A&M Consultancy</b> focuses on consultancy, sourcing, market knowledge and business support.</p><p><b>ANM Digital</b> focuses on software, SaaS, AI agents, automation, websites, mobile applications and owned digital product brands.</p></div><div className="panel"><Tag>Verifiable footprint</Tag><ul><li>Public product domains</li><li>ANM Digital GitHub organisation</li><li>Web and mobile product portfolio</li><li>Firebase and Google Cloud infrastructure</li><li>Continuous product development</li></ul><a className="textlink" href="https://github.com/ANM-Digital" target="_blank" rel="noreferrer">View the GitHub organisation →</a></div></section></Shell>}
function Contact(){return <Shell><Hero tag="Contact" title="Tell us what you want to create." copy="For product partnerships, technical collaboration and business enquiries, contact ANM Digital through the official channel below."/><section className="twocol"><div><h2>Business enquiries</h2><p>ANM Digital is operated by Yoga Products Ltd. A domain-based business email will be added before public launch.</p><a className="button" href="https://github.com/ANM-Digital" target="_blank" rel="noreferrer">ANM Digital on GitHub ↗</a></div><div className="panel"><h3>Useful details to include</h3><ul><li>The problem or opportunity</li><li>The intended users</li><li>The desired digital product</li><li>Your target timeline</li><li>Existing systems or constraints</li></ul></div></section></Shell>}
function Privacy(){return <Shell><Hero tag="Legal" title="Privacy Policy" copy="How ANM Digital handles information across this website and its digital products."/><Legal><p>Last updated: 24 August 2026</p><h2>Who we are</h2><p>ANM Digital is a digital product brand operated by Yoga Products Ltd. Individual ANM Digital products may publish additional product-specific privacy notices.</p><h2>Information we collect</h2><p>This website may collect information you voluntarily submit, basic technical logs needed for security and reliability, and aggregated analytics where enabled.</p><h2>How information is used</h2><p>Information is used to respond to enquiries, operate and secure our services, understand website performance, comply with legal obligations and improve our products.</p><h2>Advertising and Google services</h2><p>Some ANM Digital websites or applications may use Google services, including Firebase, Google Analytics, AdSense or AdMob. Where applicable, those services may process device, usage or advertising information under their own policies and the consent choices available to users.</p><h2>Your choices</h2><p>You may request access, correction or deletion of personal information, subject to applicable law and legitimate retention requirements.</p><h2>Contact</h2><p>Official privacy contact details will be published on this domain before the public launch.</p></Legal></Shell>}
function Terms(){return <Shell><Hero tag="Legal" title="Terms of Use" copy="The basic terms governing use of the ANM Digital website."/><Legal><p>Last updated: 24 August 2026</p><h2>Website use</h2><p>You may use this website for lawful informational and business purposes. You must not disrupt, misuse or attempt unauthorised access to the website or related systems.</p><h2>Product information</h2><p>Descriptions of products in development may change. Availability, pricing and product-specific terms are provided separately by each product.</p><h2>Intellectual property</h2><p>Unless otherwise stated, website content, product names, designs and software materials are owned by or licensed to Yoga Products Ltd.</p><h2>External links</h2><p>Links to third-party platforms are provided for convenience. Their services and policies are controlled by their respective operators.</p><h2>Liability</h2><p>This website is provided on an as-available basis. Nothing on it constitutes a guarantee of a particular commercial or technical outcome.</p></Legal></Shell>}
function Legal({children}:{children:React.ReactNode}){return <section className="legal">{children}</section>}
function NotFound(){return <Shell><section className="notfound"><Tag>404</Tag><h1>That page is not part of this build.</h1><Link className="button" to="/">Return home</Link></section></Shell>}

export default function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/services" element={<Services/>}/><Route path="/products" element={<Products/>}/><Route path="/about" element={<About/>}/><Route path="/contact" element={<Contact/>}/><Route path="/privacy" element={<Privacy/>}/><Route path="/terms" element={<Terms/>}/><Route path="*" element={<NotFound/>}/></Routes>}
